import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 });

    const playbooks = [
      // --- SECURITY (10) ---
      { name: "JWT Token Fix", anomaly_type: "unknown", trigger_condition: "JWT signature validation bypassed or token tampering detected", confidence_threshold: 0.92, isolation_steps: ["Revoke all active JWT tokens","Disable affected auth endpoints","Identify compromised signing keys"], healing_steps: ["Rotate JWT signing secret","Deploy patched JWT validation library","Re-issue tokens for valid sessions"], verification_steps: ["Verify token signature enforced","Confirm no bypass possible","Monitor auth failure rate"] },
      { name: "DDoS Mitigation", anomaly_type: "cpu_spike", trigger_condition: "Request rate >10000/sec from single ASN or traffic spike >500% baseline", confidence_threshold: 0.90, isolation_steps: ["Activate rate limiting at edge","Enable DDoS scrubbing","Block top offending IPs"], healing_steps: ["Apply dynamic rate limiting rules","Scale backend capacity","Gradually lift restrictions"], verification_steps: ["Verify traffic normalized","Confirm legitimate users served","Monitor attack patterns"] },
      { name: "SQL Injection Repair", anomaly_type: "unknown", trigger_condition: "SQL injection pattern detected in query parameters", confidence_threshold: 0.95, isolation_steps: ["Block source IP","Freeze affected database connections","Preserve attack payload logs"], healing_steps: ["Deploy parameterized queries","Add input sanitization layer","Patch ORM query builder"], verification_steps: ["Run injection test suite","Verify no SQLi vectors remain","Monitor query logs"] },
      { name: "Flash Loan Attack", anomaly_type: "unknown", trigger_condition: "Token price divergence >10% within single block or abnormal borrow-then-sell pattern", confidence_threshold: 0.93, isolation_steps: ["Pause affected liquidity pools","Flag suspicious oracle reads","Isolate attacker address"], healing_steps: ["Revert manipulated price feeds","Replenish drained liquidity","Patch oracle to use TWAP"], verification_steps: ["Validate price feed integrity","Confirm pool reserves match expected","Monitor for secondary manipulation"] },
      { name: "Smart Contract Reentrancy", anomaly_type: "unknown", trigger_condition: "Reentrant call pattern detected in settlement contract execution trace", confidence_threshold: 0.95, isolation_steps: ["Halt affected contract execution","Freeze associated UTXO anchors","Quarantine contract state snapshot"], healing_steps: ["Deploy reentrancy guard modifier","Replay pending tx with checks-effects-interactions pattern","Restore state from verified checkpoint"], verification_steps: ["Run reentrancy test suite","Verify no residual reentrant calls","Confirm settlement finality"] },
      { name: "XSS Prevention", anomaly_type: "unknown", trigger_condition: "Cross-site scripting payload detected in user input", confidence_threshold: 0.89, isolation_steps: ["Block affected input source","Quarantine affected sessions","Preserve payload samples"], healing_steps: ["Deploy output encoding","Add CSP headers","Patch input sanitization"], verification_steps: ["Verify XSS payloads blocked","Confirm CSP enforced","Monitor for injection attempts"] },
      { name: "CSRF Token Fix", anomaly_type: "unknown", trigger_condition: "Cross-site request forgery attempt detected", confidence_threshold: 0.87, isolation_steps: ["Block suspicious cross-origin requests","Invalidate affected sessions","Preserve request logs"], healing_steps: ["Deploy CSRF token validation","Add SameSite cookie attributes","Patch form handlers"], verification_steps: ["Verify CSRF tokens enforced","Confirm SameSite cookies","Monitor for forgery attempts"] },
      { name: "Private Key Compromise", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Private key activity from anomalous geo-location or signing anomaly", confidence_threshold: 0.97, isolation_steps: ["Immediately freeze affected wallet","Revoke all associated API tokens","Isolate key from signing infrastructure"], healing_steps: ["Generate new keypair in HSM","Rotate all dependent addresses","Migrate funds to new secure wallet"], verification_steps: ["Verify old key nullified","Confirm new key operational","Audit post-incident transactions"] },
      { name: "Multi-Sig Approval Timeout", anomaly_type: "export_pipeline_stall", trigger_condition: "Multi-sig transaction pending >30min with insufficient approvals", confidence_threshold: 0.88, isolation_steps: ["Identify pending multi-sig tx","Escalate to backup signers","Freeze tx if malicious"], healing_steps: ["Trigger backup signer rotation","Re-broadcast with refreshed nonce","Cancel and re-initiate if needed"], verification_steps: ["Verify required signatures collected","Confirm tx inclusion on-chain","Log signer response times"] },
      { name: "Oracle Manipulation Defense", anomaly_type: "unknown", trigger_condition: "Oracle price deviation >5% from consensus feeds", confidence_threshold: 0.91, isolation_steps: ["Disconnect compromised oracle","Switch to backup price feed","Flag affected settlement tx"], healing_steps: ["Recompute settlement amounts from consensus","Patch oracle aggregation logic","Replay affected settlements"], verification_steps: ["Verify price convergence","Confirm settlements match consensus","Monitor for manipulation"] },

      // --- PERFORMANCE (10) ---
      { name: "CPU Spike Throttling", anomaly_type: "cpu_spike", trigger_condition: "Node CPU utilization >90% for >60s", confidence_threshold: 0.88, isolation_steps: ["Identify CPU-intensive process","Throttle non-critical tasks","Offload work to idle nodes"], healing_steps: ["Scale horizontally","Optimize hot code paths","Restore normal CPU load"], verification_steps: ["Verify CPU <70%","Confirm no dropped requests","Monitor CPU trends"] },
      { name: "Memory Leak Remediation", anomaly_type: "agent_overload", trigger_condition: "Process memory growth >500MB/hour without release", confidence_threshold: 0.84, isolation_steps: ["Take heap snapshot","Isolate leaking process","Restart affected service"], healing_steps: ["Patch memory leak","Force garbage collection cycle","Restore service"], verification_steps: ["Verify memory stable","Confirm no leak recurrence","Monitor memory growth"] },
      { name: "Settlement Latency Recovery", anomaly_type: "latency_spike", trigger_condition: "Settlement confirmation time >5000ms threshold", confidence_threshold: 0.90, isolation_steps: ["Identify bottleneck rail","Reduce pending tx queue","Prioritize critical settlements"], healing_steps: ["Optimize rail message batching","Scale processing workers","Clear backlog"], verification_steps: ["Verify settlement time <3000ms","Confirm no stuck transactions","Monitor latency trends"] },
      { name: "Disk Space Exhaustion", anomaly_type: "export_pipeline_stall", trigger_condition: "Disk usage >90% on critical volume", confidence_threshold: 0.88, isolation_steps: ["Identify large files/logs","Compress or archive old data","Clear temporary files"], healing_steps: ["Expand disk capacity","Implement log rotation","Restore disk headroom"], verification_steps: ["Verify disk usage <70%","Confirm no write failures","Monitor disk growth"] },
      { name: "Token Usage Overrun", anomaly_type: "token_overrun", trigger_condition: "Agent token consumption exceeds budget >120%", confidence_threshold: 0.85, isolation_steps: ["Throttle agent request rate","Switch to compact prompt mode","Identify high-consumption agent"], healing_steps: ["Optimize prompt templates","Reduce context window size","Apply token budget enforcement"], verification_steps: ["Verify token usage within budget","Confirm agent response quality","Monitor consumption rate"] },
      { name: "Database Query Slowdown", anomaly_type: "latency_spike", trigger_condition: "Avg query latency >1000ms", confidence_threshold: 0.87, isolation_steps: ["Identify slow queries via EXPLAIN","Add missing indexes","Isolate heavy queries"], healing_steps: ["Optimize query plans","Cache frequent results","Rebuild fragmented indexes"], verification_steps: ["Verify query latency <200ms","Confirm index hit ratio >95%","Monitor query performance"] },
      { name: "Network Congestion Relief", anomaly_type: "latency_spike", trigger_condition: "Network round-trip >500ms for inter-service calls", confidence_threshold: 0.86, isolation_steps: ["Identify congested path","Reduce inter-service call frequency","Enable connection pooling"], healing_steps: ["Apply request batching","Switch to compressed transport","Restore normal RTT"], verification_steps: ["Verify RTT <100ms","Confirm no packet loss","Monitor network health"] },
      { name: "Event Queue Backlog Drain", anomaly_type: "export_pipeline_stall", trigger_condition: "Event queue depth >10000 pending messages", confidence_threshold: 0.83, isolation_steps: ["Scale event consumers","Pause non-critical producers","Prioritize settlement events"], healing_steps: ["Drain backlog with burst consumers","Optimize consumer throughput","Restore queue depth"], verification_steps: ["Verify queue depth <1000","Confirm no message loss","Monitor queue health"] },
      { name: "Cache Hit Rate Degradation", anomaly_type: "latency_spike", trigger_condition: "Cache hit ratio drops below 80%", confidence_threshold: 0.81, isolation_steps: ["Analyze cache miss patterns","Increase cache TTL for stable data","Identify evicted entries"], healing_steps: ["Expand cache capacity","Optimize cache key strategy","Restore hit ratio"], verification_steps: ["Verify cache hit >90%","Confirm reduced DB load","Monitor cache performance"] },
      { name: "Thread Pool Starvation", anomaly_type: "agent_overload", trigger_condition: "Thread pool queue depth >1000", confidence_threshold: 0.82, isolation_steps: ["Identify blocking operations","Increase thread pool size","Isolate long-running tasks"], healing_steps: ["Convert blocking to async","Right-size thread pool","Restore normal queue depth"], verification_steps: ["Verify queue depth <100","Confirm no blocked threads","Monitor thread pool"] },

      // --- QUANTUM (10) ---
      { name: "RSA to PQC Migration", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "RSA-2048 key identified as quantum-vulnerable", confidence_threshold: 0.94, isolation_steps: ["Inventory all RSA key usage","Generate Kyber keypairs in HSM","Schedule migration window"], healing_steps: ["Deploy Kyber-based key exchange","Update TLS configurations","Decommission RSA keys"], verification_steps: ["Verify Kyber key exchange active","Confirm no RSA dependencies","Test quantum resistance"] },
      { name: "ECDSA to Dilithium Migration", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "ECDSA signatures identified as quantum-vulnerable", confidence_threshold: 0.93, isolation_steps: ["Inventory ECDSA signing operations","Generate Dilithium keypairs","Stage signature migration"], healing_steps: ["Deploy Dilithium signing","Update verification logic","Archive ECDSA keys"], verification_steps: ["Verify Dilithium signatures valid","Confirm backward compatibility","Monitor signing performance"] },
      { name: "SPHINCS+ Deployment", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Need stateless hash-based PQC signatures for long-term archival", confidence_threshold: 0.90, isolation_steps: ["Assess archival signing requirements","Provision HSM for SPHINCS+","Test signature size benchmarks"], healing_steps: ["Deploy SPHINCS+ for archival signatures","Update verification endpoints","Remove hash-vulnerable algorithms"], verification_steps: ["Verify SPHINCS+ signatures valid","Confirm signature sizes acceptable","Monitor verification performance"] },
      { name: "Post-Quantum Key Rotation", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Cryptographic keys overdue for post-quantum rotation", confidence_threshold: 0.88, isolation_steps: ["Identify keys needing rotation","Generate new PQC keypairs","Preserve old keys for transition"], healing_steps: ["Rotate keys to PQC algorithms","Update DID documents","Verify key rotation complete"], verification_steps: ["Verify new keys active","Confirm old keys archived","Monitor key rotation schedule"] },
      { name: "Shor's Algorithm Defense", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Cryptanalysis: algorithm vulnerable to Shor's factoring", confidence_threshold: 0.95, isolation_steps: ["Identify all vulnerable algorithms","Prioritize by exposure level","Plan migration sequence"], healing_steps: ["Deploy post-quantum alternatives","Update key generation","Remove vulnerable algorithms"], verification_steps: ["Verify PQC algorithms in use","Confirm no Shor-vulnerable crypto","Monitor crypto inventory"] },
      { name: "Grover's Algorithm Assessment", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Symmetric key length insufficient against Grover acceleration", confidence_threshold: 0.91, isolation_steps: ["Assess symmetric key lengths","Identify AES-128 usage","Plan key length upgrade"], healing_steps: ["Upgrade to AES-256","Double hash iterations","Restore quantum-resistant security"], verification_steps: ["Verify key lengths >=256 bits","Confirm no weakened algorithms","Monitor crypto strength"] },
      { name: "Post-Quantum TLS Migration", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "TLS using quantum-vulnerable cipher suites", confidence_threshold: 0.92, isolation_steps: ["Inventory TLS configurations","Identify quantum-vulnerable suites","Plan PQC TLS upgrade"], healing_steps: ["Deploy hybrid PQC TLS","Update certificate chain","Verify TLS handshake"], verification_steps: ["Verify PQC TLS active","Confirm no downgrade possible","Monitor TLS security"] },
      { name: "Lattice-Based Crypto Deploy", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Need NIST PQC standard lattice-based algorithms", confidence_threshold: 0.90, isolation_steps: ["Evaluate lattice algorithm options","Provision HSM support","Test performance benchmarks"], healing_steps: ["Deploy ML-KEM and ML-DSA","Update cryptographic library","Remove legacy algorithms"], verification_steps: ["Verify lattice crypto operational","Confirm performance acceptable","Monitor crypto operations"] },
      { name: "Quantum-Safe Blockchain Signing", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Blockchain signatures using quantum-vulnerable curves", confidence_threshold: 0.91, isolation_steps: ["Assess blockchain signing algorithms","Identify secp256k1 usage","Plan PQC signing migration"], healing_steps: ["Deploy PQC signature scheme","Update blockchain validators","Test signature verification"], verification_steps: ["Verify PQC signatures on-chain","Confirm validator consensus","Monitor signing performance"] },
      { name: "Hybrid Crypto Transition", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Need hybrid classical plus PQC during migration period", confidence_threshold: 0.88, isolation_steps: ["Assess migration timeline","Deploy hybrid key exchange","Test dual-signature verification"], healing_steps: ["Enable classical and PQC dual signatures","Gradually phase out classical","Monitor transition"], verification_steps: ["Verify hybrid signatures valid","Confirm migration progress","Monitor classical usage decline"] },

      // --- CORE (10) ---
      { name: "Service Restart Recovery", anomaly_type: "heartbeat_miss", trigger_condition: "Service heartbeat lost >60s", confidence_threshold: 0.86, isolation_steps: ["Identify stopped service","Redirect traffic to healthy instances","Preserve service state"], healing_steps: ["Diagnose stop cause","Restart service with health checks","Restore traffic"], verification_steps: ["Verify service heartbeat active","Confirm health checks passing","Monitor service stability"] },
      { name: "Circuit Breaker Reset", anomaly_type: "integration_degraded", trigger_condition: "Circuit breaker tripped due to cascading failures", confidence_threshold: 0.85, isolation_steps: ["Identify failure cause","Switch to fallback service","Preserve request queue"], healing_steps: ["Fix underlying failures","Reset circuit breaker","Restore normal service"], verification_steps: ["Verify circuit closed","Confirm service stable","Monitor failure rate"] },
      { name: "Rollback Deployment", anomaly_type: "unknown", trigger_condition: "Deployment causing errors or service degradation", confidence_threshold: 0.89, isolation_steps: ["Identify problematic deployment","Freeze new deployments","Preserve previous version"], healing_steps: ["Roll back to previous version","Verify service restored","Diagnose deployment issue"], verification_steps: ["Verify service healthy","Confirm rollback successful","Monitor error rates"] },
      { name: "Heartbeat Recovery", anomaly_type: "heartbeat_miss", trigger_condition: "Agent or node heartbeat missed >90s", confidence_threshold: 0.88, isolation_steps: ["Identify missing heartbeat source","Mark node as degraded","Preserve last known state"], healing_steps: ["Restore network connectivity","Re-establish heartbeat signal","Verify node responsive"], verification_steps: ["Verify heartbeat active","Confirm node healthy","Monitor heartbeat interval"] },
      { name: "Orphan Node Cleanup", anomaly_type: "node_orphan", trigger_condition: "Node marked orphaned with no heartbeat >180s", confidence_threshold: 0.89, isolation_steps: ["Identify orphaned node","Redirect traffic away","Preserve node state snapshot"], healing_steps: ["Re-establish node connectivity","Re-sync node state with cluster","Re-join node to orchestrator"], verification_steps: ["Verify node rejoined","Confirm state consistency","Monitor node stability"] },
      { name: "Agent Overload Rebalancing", anomaly_type: "agent_overload", trigger_condition: "Agent task queue >80% capacity", confidence_threshold: 0.84, isolation_steps: ["Identify overloaded agent","Redistribute tasks to idle agents","Throttle incoming requests"], healing_steps: ["Scale agent horizontally","Optimize task processing","Restore normal load"], verification_steps: ["Verify agent load <60%","Confirm task completion rates","Monitor agent capacity"] },
      { name: "Prompt Drift Correction", anomaly_type: "prompt_drift", trigger_condition: "Agent response quality degraded >15% from baseline", confidence_threshold: 0.87, isolation_steps: ["Capture drifted prompt versions","Compare to baseline prompts","Identify drift source"], healing_steps: ["Revert to stable prompt template","Apply prompt guardrails","Restore response quality"], verification_steps: ["Verify response quality at baseline","Confirm no drift recurrence","Monitor prompt performance"] },
      { name: "Export Pipeline Stall Fix", anomaly_type: "export_pipeline_stall", trigger_condition: "Export pipeline stalled with no progress >5min", confidence_threshold: 0.83, isolation_steps: ["Identify stall point in pipeline","Pause new exports","Preserve pipeline state"], healing_steps: ["Fix pipeline blocker","Resume export processing","Clear stalled items"], verification_steps: ["Verify pipeline flowing","Confirm exports completing","Monitor pipeline throughput"] },
      { name: "Integration Degraded Recovery", anomaly_type: "integration_degraded", trigger_condition: "External integration response time >5000ms or error rate >10%", confidence_threshold: 0.86, isolation_steps: ["Identify degraded integration","Switch to backup if available","Queue pending requests"], healing_steps: ["Fix integration connectivity","Restore normal response times","Clear request queue"], verification_steps: ["Verify integration responsive","Confirm error rate <1%","Monitor integration health"] },
      { name: "Node Provisioning", anomaly_type: "node_orphan", trigger_condition: "New node needs provisioning to handle load", confidence_threshold: 0.82, isolation_steps: ["Assess capacity needs","Provision new node","Configure node parameters"], healing_steps: ["Deploy node image","Join node to cluster","Distribute load to new node"], verification_steps: ["Verify node active in cluster","Confirm load distributed","Monitor node performance"] },

      // --- BLOCKCHAIN (10) ---
      { name: "Bitcoin Anchor Node Failure", anomaly_type: "heartbeat_miss", trigger_condition: "Bitcoin anchor node unreachable >120s", confidence_threshold: 0.92, isolation_steps: ["Switch to backup Bitcoin node","Freeze new anchor operations","Preserve UTXO state"], healing_steps: ["Restore Bitcoin node connectivity","Re-sync blockchain state","Resume anchoring"], verification_steps: ["Verify Bitcoin node synced","Confirm anchor operations resumed","Monitor node health"] },
      { name: "Multi-Sig Approval Timeout Recovery", anomaly_type: "export_pipeline_stall", trigger_condition: "Multi-sig transaction stuck pending >30min with insufficient approvals", confidence_threshold: 0.88, isolation_steps: ["Identify pending multi-sig tx","Escalate to backup signers","Freeze tx if malicious"], healing_steps: ["Trigger backup signer rotation","Re-broadcast with refreshed nonce","Cancel and re-initiate if needed"], verification_steps: ["Verify required signatures collected","Confirm tx inclusion on-chain","Log signer response times"] },
      { name: "OFAC Sanctions Screening", anomaly_type: "unknown", trigger_condition: "Transaction matched OFAC sanctions screening list", confidence_threshold: 0.93, isolation_steps: ["Immediately freeze transaction","Escalate to compliance officer","File sanctions report"], healing_steps: ["Conduct enhanced screening","Confirm true or false positive","Release or block permanently"], verification_steps: ["Verify sanctions check complete","Confirm regulatory compliance","Monitor for related hits"] },
      { name: "SEC Disclosure Filing", anomaly_type: "unknown", trigger_condition: "SEC disclosure filing deadline approaching or filing failed", confidence_threshold: 0.90, isolation_steps: ["Identify disclosure requirements","Prepare filing data","Escalate to legal team"], healing_steps: ["Complete SEC disclosure filing","Submit within deadline","Verify filing accepted"], verification_steps: ["Verify filing submitted","Confirm SEC acceptance","Monitor filing status"] },
      { name: "XRP Ledger Connectivity Loss", anomaly_type: "integration_degraded", trigger_condition: "XRP ledger connection lost", confidence_threshold: 0.90, isolation_steps: ["Switch to backup XRP node","Freeze XRP settlement queue","Preserve transaction state"], healing_steps: ["Restore XRP ledger connection","Re-sync ledger state","Resume XRP settlements"], verification_steps: ["Verify XRP connection stable","Confirm ledger synced","Monitor XRP connectivity"] },
      { name: "Smart Contract Pausing", anomaly_type: "unknown", trigger_condition: "Emergency pause needed for compromised smart contract", confidence_threshold: 0.91, isolation_steps: ["Identify compromised contract","Execute emergency pause","Freeze associated UTXO anchors"], healing_steps: ["Patch contract vulnerability","Test fix on testnet","Unpause with monitoring"], verification_steps: ["Verify contract paused","Confirm fix deployed","Monitor contract activity"] },
      { name: "Bridge Validator Key Compromise", anomaly_type: "quantum_vulnerability_detected", trigger_condition: "Bridge validator signing anomaly detected", confidence_threshold: 0.96, isolation_steps: ["Freeze bridge validator set","Halt cross-chain message queue","Isolate compromised validator"], healing_steps: ["Rotate validator keypair","Re-attest bridge state with new keys","Replay queued messages"], verification_steps: ["Verify all validators re-attested","Confirm bridge state consistency","Test cross-chain message flow"] },
      { name: "Cross-Chain State Desync", anomaly_type: "integration_degraded", trigger_condition: "Bridge state divergence between chains detected", confidence_threshold: 0.90, isolation_steps: ["Halt bridge operations","Compare state roots across chains","Identify divergence point"], healing_steps: ["Re-sync state from canonical chain","Replay missed messages","Restore bridge consistency"], verification_steps: ["Verify state roots match","Confirm bridge operational","Test cross-chain consistency"] },
      { name: "Settlement Failure Retry", anomaly_type: "export_pipeline_stall", trigger_condition: "Settlement transaction failed on rail", confidence_threshold: 0.90, isolation_steps: ["Identify failure reason","Preserve transaction state","Queue for retry"], healing_steps: ["Fix underlying failure cause","Re-submit settlement with adjusted params","Confirm settlement"], verification_steps: ["Verify settlement confirmed on-chain","Confirm receipt generated","Monitor retry success rate"] },
      { name: "UTXO Binding Repair", anomaly_type: "unknown", trigger_condition: "Gold asset Satoshi UTXO binding broken", confidence_threshold: 0.91, isolation_steps: ["Identify broken UTXO binding","Freeze affected gold asset","Preserve binding state"], healing_steps: ["Re-bind gold asset to valid UTXO","Update binding hash","Verify anchor chain"], verification_steps: ["Verify UTXO binding restored","Confirm gold asset integrity","Monitor binding stability"] }
    ];

    const created = await base44.asServiceRole.entities.AegisPlaybook.bulkCreate(playbooks);
    return Response.json({ status: 'success', created: created.length, total_playbooks: playbooks.length });
  } catch (error) {
    return Response.json({ error: error.message, stack: error.stack }, { status: 500 });
  }
}